export const initialRequests = {
  holidays: [
    {
      id: "HOL-001",
      title: "Christmas Holiday Request",
      status: "PENDING",
      priority: 2,
      assignee: "JD",
      type: "ANNUAL_LEAVE",
      dates: "Dec 23 - Jan 2",
    },
    {
      id: "HOL-002",
      title: "Summer Vacation",
      status: "APPROVED",
      priority: 1,
      assignee: "SM",
      type: "VACATION",
      dates: "Jul 15 - Jul 29",
    },
    {
      id: "HOL-003",
      title: "Sick Leave Request",
      status: "TO DO",
      priority: 3,
      assignee: "AB",
      type: "SICK_LEAVE",
      dates: "Dec 20",
    },
  ],
  equipment: [
    {
      id: "EQP-001",
      title: "New MacBook Pro Request",
      status: "IN_REVIEW",
      priority: 2,
      assignee: "TK",
      type: "HARDWARE",
      department: "Engineering",
    },
    {
      id: "EQP-002",
      title: "Office Chair Replacement",
      status: "APPROVED",
      priority: 1,
      assignee: "MR",
      type: "FURNITURE",
      department: "HR",
    },
    {
      id: "EQP-003",
      title: "Software License - Adobe Creative",
      status: "PENDING",
      priority: 2,
      assignee: "LW",
      type: "SOFTWARE",
      department: "Design",
    },
  ],
  other: [
    {
      id: "OTH-001",
      title: "Remote Work Setup",
      status: "TO DO",
      priority: 1,
      assignee: "PJ",
      type: "WORKSPACE",
      description: "Home office setup approval",
    },
    {
      id: "OTH-002",
      title: "Training Course Request",
      status: "APPROVED",
      priority: 2,
      assignee: "NK",
      type: "TRAINING",
      description: "React Advanced Workshop",
    },
    {
      id: "OTH-003",
      title: "Parking Spot Assignment",
      status: "PENDING",
      priority: 3,
      assignee: "RH",
      type: "FACILITIES",
      description: "Reserved parking space",
    },
  ],
}
