export const mockRequests = [
    {
      id: "req-001",
      title: "New Laptop Request",
      requester: "John Smith",
      assetType: "Laptop",
      description: "Need a new MacBook Pro for development work",
      date: "2025-05-01",
      priority: "high",
      status: "pending",
    },
    {
      id: "req-002",
      title: "Monitor Request",
      requester: "Sarah Johnson",
      assetType: "Monitor",
      description: "Requesting a 27-inch monitor for design work",
      date: "2025-05-02",
      priority: "medium",
      status: "pending",
    },
    {
      id: "req-003",
      title: "Office Chair",
      requester: "Michael Brown",
      assetType: "Furniture",
      description: "Need an ergonomic chair for back support",
      date: "2025-05-03",
      priority: "low",
      status: "pending",
    },
    {
      id: "req-004",
      title: "Software License",
      requester: "Emily Davis",
      assetType: "Software",
      description: "Adobe Creative Cloud license for design team",
      date: "2025-04-28",
      priority: "high",
      status: "approved",
    },
    {
      id: "req-005",
      title: "Wireless Keyboard",
      requester: "David Wilson",
      assetType: "Peripherals",
      description: "Wireless keyboard for remote work setup",
      date: "2025-04-29",
      priority: "low",
      status: "approved",
    },
    {
      id: "req-006",
      title: "Tablet Device",
      requester: "Jennifer Lee",
      assetType: "Tablet",
      description: "iPad Pro for client presentations",
      date: "2025-04-25",
      priority: "medium",
      status: "rejected",
    },
    {
      id: "req-007",
      title: "Desk Phone",
      requester: "Robert Taylor",
      assetType: "Communication",
      description: "VoIP phone for office desk",
      date: "2025-04-26",
      priority: "low",
      status: "rejected",
    },
    {
      id: "req-008",
      title: "Wireless Headphones",
      requester: "Lisa Anderson",
      assetType: "Audio",
      description: "Noise-cancelling headphones for open office",
      date: "2025-05-04",
      priority: "medium",
      status: "pending",
    },
    {
      id: "req-009",
      title: "Docking Station",
      requester: "Kevin Martin",
      assetType: "Peripherals",
      description: "USB-C docking station for laptop",
      date: "2025-04-30",
      priority: "medium",
      status: "approved",
    },
  ]
  